{{- if .Values.weaviate.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "consultant-matcher.fullname" . }}-weaviate
  labels:
    {{- include "consultant-matcher.labels" . | nindent 4 }}
    component: weaviate
spec:
  type: {{ .Values.weaviate.service.type }}
  ports:
    - port: {{ .Values.weaviate.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "consultant-matcher.selectorLabels" . | nindent 4 }}
    component: weaviate
{{- end }}
